export * from './project-add/project-add.component';
export * from './project-add/project-add.route';
export * from './project-edit/project-edit.component';
export * from './project-edit/project-edit.route';
export * from './project-list/project-list.component';
export * from './project-list/project-list.route';
export * from './project-view/project-view.component';
export * from './project-view/project-view.route';
export * from './projects.route';
