export * from './add/add.component';
export * from './add/add.route';
export * from './edit/edit.component';
export * from './edit/edit.route';
export * from './list/list.component';
export * from './list/list.route';
export * from './view/view.component';
export * from './view/view.route';
export * from './projects.route';
